/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ESSSigningCertificateV2Module"
 * 	found in "ESSSigningCertificateV2.asn1"
 * 	`asn1c -pdu=SigningCertificateV2`
 */

#ifndef	_CountryName_H_
#define	_CountryName_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NumericString.h>
#include <PrintableString.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CountryName_PR {
	CountryName_PR_NOTHING,	/* No components present */
	CountryName_PR_x121_dcc_code,
	CountryName_PR_iso_3166_alpha2_code
} CountryName_PR;

/* CountryName */
typedef struct CountryName {
	CountryName_PR present;
	union CountryName_u {
		NumericString_t	 x121_dcc_code;
		PrintableString_t	 iso_3166_alpha2_code;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CountryName_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CountryName;

#ifdef __cplusplus
}
#endif

#endif	/* _CountryName_H_ */
#include <asn_internal.h>
