/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ESSSigningCertificateV2Module"
 * 	found in "ESSSigningCertificateV2.asn1"
 * 	`asn1c -pdu=SigningCertificateV2`
 */

#ifndef	_OtherName_H_
#define	_OtherName_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OBJECT_IDENTIFIER.h>
#include <ANY.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* OtherName */
typedef struct OtherName {
	OBJECT_IDENTIFIER_t	 type_id;
	ANY_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} OtherName_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OtherName;

#ifdef __cplusplus
}
#endif

#endif	/* _OtherName_H_ */
#include <asn_internal.h>
