/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ESSSigningCertificateV2Module"
 * 	found in "ESSSigningCertificateV2.asn1"
 * 	`asn1c -pdu=SigningCertificateV2`
 */

#ifndef	_PolicyInformation_H_
#define	_PolicyInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CertPolicyId.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PolicyQualifierInfo;

/* PolicyInformation */
typedef struct PolicyInformation {
	CertPolicyId_t	 policyIdentifier;
	struct policyQualifiers {
		A_SEQUENCE_OF(struct PolicyQualifierInfo) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *policyQualifiers;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PolicyInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PolicyInformation;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PolicyQualifierInfo.h"

#endif	/* _PolicyInformation_H_ */
#include <asn_internal.h>
