/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ESSSigningCertificateV2Module"
 * 	found in "ESSSigningCertificateV2.asn1"
 * 	`asn1c -pdu=SigningCertificateV2`
 */

#ifndef	_PolicyQualifierInfo_H_
#define	_PolicyQualifierInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PolicyQualifierId.h"
#include <ANY.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PolicyQualifierInfo */
typedef struct PolicyQualifierInfo {
	PolicyQualifierId_t	 policyQualifierId;
	ANY_t	 qualifier;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PolicyQualifierInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PolicyQualifierInfo;

#ifdef __cplusplus
}
#endif

#endif	/* _PolicyQualifierInfo_H_ */
#include <asn_internal.h>
